title: Anthony Leray
description: Portfolio Data Analyst | SQL - Power BI - Python
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
# Optionnel : pour s'assurer que les liens relatifs fonctionnent bien
relative_links:
  enabled: true
  convertToHtml: true
